#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (51.85%)
# Total Accepted:    118.8K
# Total Submissions: 229.2K
# Testcase Example:  '"abcd"\n"abcde"'
#
#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
#
#
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        map = collections.Counter()
        for c in s:
            map[c] += 1
        for c in t:
            map[c] -= 1
        for (elem, cnt) in map.items():
            if cnt != 0:
                return elem
        return None


# More concise version of above solution (collections.Counter(string))
#
# https://leetcode.com/problems/find-the-difference/discuss/86845/1-liners-and-2-liner-in-Python
#
# class Solution(object):
#    def findTheDifference(self, s, t):
#        return list((collections.Counter(t) - collections.Counter(s)))[0]
