/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (51.85%)
 * Total Accepted:    118.8K
 * Total Submissions: 229.2K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */

static auto x = []() {
  std::ios::sync_with_stdio(false);
  cin.tie(NULL);
  return nullptr;
}();

/**
 *  Hash Map
 *
 *  Time: O(n)
 *  Space: O(n)
 */
class Solution {
 public:
  char findTheDifference(string s, string t) {
    unordered_map<char, int> freq;
    for (const char c : s) {
      ++freq[c];
    }

    for (const char c : t) {
      --freq[c];
    }

    for (const auto& f : freq) {
      if (f.second != 0) {
        return f.first;
      }
    }
    return '\0';
  }
};
